-- Safe initialization: only creates database/user/schema if missing
-- Does NOT drop existing data (idempotent for production)

CREATE DATABASE IF NOT EXISTS otptestdb;
USE otptestdb;

CREATE USER IF NOT EXISTS 'otptestuser'@'%' IDENTIFIED BY 'testpass';
GRANT ALL PRIVILEGES ON otptestdb.* TO 'otptestuser'@'%';
FLUSH PRIVILEGES;

-- ---------------------------------------------------------
-- Table Structures
-- ---------------------------------------------------------

CREATE TABLE IF NOT EXISTS users (
                                     user_id INT AUTO_INCREMENT PRIMARY KEY,
                                     username VARCHAR(50) UNIQUE NOT NULL,
                                     password_hash VARCHAR(255) NOT NULL,
                                     email VARCHAR(100) UNIQUE NOT NULL,
                                     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS classes (
                                       class_id INT AUTO_INCREMENT PRIMARY KEY,
                                       class_name VARCHAR(100) UNIQUE NOT NULL,
                                       creator_id INT,
                                       topic VARCHAR(100),
                                       created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                       FOREIGN KEY (creator_id) REFERENCES users(user_id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS participants (
                                            user_id INT,
                                            class_id INT,
                                            PRIMARY KEY (user_id, class_id),
                                            FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
                                            FOREIGN KEY (class_id) REFERENCES classes(class_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS materials (
                                         file_id INT AUTO_INCREMENT PRIMARY KEY,
                                         original_filename VARCHAR(255) NOT NULL,
                                         stored_filename VARCHAR(100) NOT NULL,
                                         filepath VARCHAR(512),
                                         material_type VARCHAR(100),
                                         uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                         class_id INT,
                                         user_id INT NULL,
                                         FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE SET NULL,
                                         FOREIGN KEY (class_id) REFERENCES classes(class_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS reviews (
                                       review_id INT AUTO_INCREMENT PRIMARY KEY,
                                       review TEXT,
                                       rating INT CHECK (rating >= 0 AND rating <= 5),
                                       file_id INT,
                                       user_id INT NULL,
                                       created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                       FOREIGN KEY (file_id) REFERENCES materials(file_id) ON DELETE CASCADE,
                                       FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS localization_strings (
                                                    id INT AUTO_INCREMENT PRIMARY KEY,
                                                    translation_key VARCHAR(100) NOT NULL,
                                                    value VARCHAR(500) NOT NULL,
                                                    language VARCHAR(10) NOT NULL,
                                                    UNIQUE KEY unique_key_lang (translation_key, language)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- ---------------------------------------------------------
-- Seed Data: Localization
-- ---------------------------------------------------------

INSERT INTO localization_strings (translation_key, value, language) VALUES
-- General App & Topbar
('app.title', 'Learning Platform', 'en'),
('app.title', 'پلتفرم یادگیری', 'fa'),
('app.title', 'Plateforme d''apprentissage', 'fr'),
('app.title', 'Платформа обучения', 'ru'),
('topbar.title', 'LearnHub', 'en'),
('topbar.title', 'LearnHub', 'fa'),
('topbar.title', 'LearnHub', 'fr'),
('topbar.title', 'LearnHub', 'ru'),
('topbar.subtitle', 'Learning Platform', 'en'),
('topbar.subtitle', 'پلتفرم یادگیری', 'fa'),
('topbar.subtitle', 'Plateforme d''apprentissage', 'fr'),
('topbar.subtitle', 'Платформа обучения', 'ru'),
('topbar.profile', 'Profile', 'en'),
('topbar.profile', 'پروفایل', 'fa'),
('topbar.profile', 'Profil', 'fr'),
('topbar.profile', 'Профиль', 'ru'),
('topbar.login', 'Log in', 'en'),
('topbar.login', 'ورود', 'fa'),
('topbar.login', 'Connexion', 'fr'),
('topbar.login', 'Войти', 'ru'),
('topbar.language', 'Language', 'en'),
('topbar.language', 'زبان', 'fa'),
('topbar.language', 'Langue', 'fr'),
('topbar.language', 'Язык', 'ru'),
('topbar.language.english', 'English', 'en'),
('topbar.language.english', 'English', 'fa'),
('topbar.language.english', 'English', 'fr'),
('topbar.language.english', 'English', 'ru'),
('topbar.language.french', 'Français', 'en'),
('topbar.language.french', 'Français', 'fa'),
('topbar.language.french', 'Français', 'fr'),
('topbar.language.french', 'Français', 'ru'),
('topbar.language.persian', 'فارسی', 'en'),
('topbar.language.persian', 'فارسی', 'fa'),
('topbar.language.persian', 'فارسی', 'fr'),
('topbar.language.persian', 'فارسی', 'ru'),
('topbar.language.russian', 'Русский', 'en'),
('topbar.language.russian', 'Русский', 'fa'),
('topbar.language.russian', 'Русский', 'fr'),
('topbar.language.russian', 'Русский', 'ru'),

-- Main Hero Section
('main.hero.title', 'Master New Skills Faster.', 'en'),
('main.hero.title', 'مهارت هاي جديد را سريع تر بياموزيد.', 'fa'),
('main.hero.title', 'Maîtrisez de nouvelles compétences plus rapidement.', 'fr'),
('main.hero.title', 'Осваивайте новые навыки быстрее.', 'ru'),
('main.hero.subtitle', 'Access courses, share materials, and learn with peers. Join over 5 million learners worldwide.', 'en'),
('main.hero.subtitle', 'به دوره ها دسترسي پيدا کنيد، محتواي آموزشي را به اشتراک بگذاريد و با همتايان خود ياد بگيريد.', 'fa'),
('main.hero.subtitle', 'Accédez à des cours, partagez des ressources et apprenez avec vos pairs. Rejoignez plus de 5 millions d''apprenants dans le monde.', 'fr'),
('main.hero.subtitle', 'Получайте доступ к курсам, делитесь материалами и учитесь вместе с другими. Присоединяйтесь к более чем 5 миллионам учащихся по всему миру.', 'ru'),
('main.hero.getStarted', 'Get Started Free', 'en'),
('main.hero.getStarted', 'شروع رایگان', 'fa'),
('main.hero.getStarted', 'Commencer gratuitement', 'fr'),
('main.hero.getStarted', 'Начать бесплатно', 'ru'),
('main.hero.signIn', 'Sign In', 'en'),
('main.hero.signIn', 'ورود', 'fa'),
('main.hero.signIn', 'Se connecter', 'fr'),
('main.hero.signIn', 'Войти', 'ru'),
('main.cards.library.title', 'Rich Course Library', 'en'),
('main.cards.library.title', 'کتابخانه دوره غني', 'fa'),
('main.cards.library.title', 'Bibliothèque de cours riche', 'fr'),
('main.cards.library.title', 'Богатая библиотека курсов', 'ru'),
('main.cards.library.desc', 'Browse and enroll in classes taught by experienced creators.', 'en'),
('main.cards.library.desc', 'دوره ها را مرور کرده و در کلاس ها ثبت نام کنيد.', 'fa'),
('main.cards.library.desc', 'Parcourez et inscrivez-vous à des classes dispensées par des créateurs expérimentés.', 'fr'),
('main.cards.library.desc', 'Просматривайте и записывайтесь на занятия от опытных авторов.', 'ru'),
('main.cards.instructors.title', 'Expert Instructors', 'en'),
('main.cards.instructors.title', 'مدرسان متخصص', 'fa'),
('main.cards.instructors.title', 'Instructeurs experts', 'fr'),
('main.cards.instructors.title', 'Экспертные преподаватели', 'ru'),
('main.cards.instructors.desc', 'Learn directly from practitioners in their fields.', 'en'),
('main.cards.instructors.desc', 'از اساتيد مجرب بياموزيد.', 'fa'),
('main.cards.instructors.desc', 'Apprenez directement des praticiens de leur domaine.', 'fr'),
('main.cards.instructors.desc', 'Учитесь напрямую у практиков в своей области.', 'ru'),
('main.cards.reviews.title', 'Peer Reviews', 'en'),
('main.cards.reviews.title', 'نقدهای همتا', 'fa'),
('main.cards.reviews.title', 'Avis des pairs', 'fr'),
('main.cards.reviews.title', 'Отзывы участников', 'ru'),
('main.cards.reviews.desc', 'Rate and review class materials to help everyone improve.', 'en'),
('main.cards.reviews.desc', 'مواد آموزشي را ارزيابي کنيد و به بهبود همه کمک کنيد.', 'fa'),
('main.cards.reviews.desc', 'Évaluez et commentez les ressources pour aider tout le monde à s''améliorer.', 'fr'),
('main.cards.reviews.desc', 'Оценивайте и комментируйте учебные материалы, помогая всем учиться лучше.', 'ru'),
('main.section.title', 'Everything you need to learn', 'en'),
('main.section.title', 'همه چيزهايي که براي يادگيري نياز داريد', 'fa'),
('main.section.title', 'Tout ce dont vous avez besoin pour apprendre', 'fr'),
('main.section.title', 'Все, что нужно для обучения', 'ru'),

-- Login Page
('login.welcome', 'Welcome back', 'en'),
('login.welcome', 'خوش آمدید', 'fa'),
('login.welcome', 'Content de vous revoir', 'fr'),
('login.welcome', 'С возвращением', 'ru'),
('login.subtitle', 'Sign in to your account to continue.', 'en'),
('login.subtitle', 'برای ادامه وارد حساب خود شوید.', 'fa'),
('login.subtitle', 'Connectez-vous à votre compte pour continuer.', 'fr'),
('login.subtitle', 'Войдите в свой аккаунт, чтобы продолжить.', 'ru'),
('login.username', 'Username', 'en'),
('login.username', 'نام کاربری', 'fa'),
('login.username', 'Nom d''utilisateur', 'fr'),
('login.username', 'Имя пользователя', 'ru'),
('login.password', 'Password', 'en'),
('login.password', 'رمز عبور', 'fa'),
('login.password', 'Mot de passe', 'fr'),
('login.password', 'Пароль', 'ru'),
('login.signIn', 'Sign In', 'en'),
('login.signIn', 'ورود', 'fa'),
('login.signIn', 'Se connecter', 'fr'),
('login.signIn', 'Войти', 'ru'),
('login.registerNow', 'Register Now', 'en'),
('login.registerNow', 'ثبت نام', 'fa'),
('login.registerNow', 'Inscrivez-vous', 'fr'),
('login.registerNow', 'Зарегистрироваться', 'ru'),
('login.noAccount', 'Don''t have an account?', 'en'),
('login.noAccount', 'حساب ندارید؟', 'fa'),
('login.noAccount', 'Vous n''avez pas de compte ?', 'fr'),
('login.noAccount', 'Нет аккаунта?', 'ru'),
('login.username.prompt', 'Enter your username', 'en'),
('login.username.prompt', 'نام کاربری خود را وارد کنید', 'fa'),
('login.username.prompt', 'Entrez votre nom d''utilisateur', 'fr'),
('login.username.prompt', 'Введите имя пользователя', 'ru'),
('login.password.prompt', 'Enter your password', 'en'),
('login.password.prompt', 'رمز عبور خود را وارد کنید', 'fa'),
('login.password.prompt', 'Entrez votre mot de passe', 'fr'),
('login.password.prompt', 'Введите пароль', 'ru'),
('login.confirmPassword', 'Confirm Password', 'en'),
('login.confirmPassword', 'تأیید رمز عبور', 'fa'),
('login.confirmPassword', 'Confirmez le mot de passe', 'fr'),
('login.confirmPassword', 'Подтвердите пароль', 'ru'),
('login.error.required', 'Username and password required', 'en'),
('login.error.required', 'نام کاربری و رمز عبور لازم است', 'fa'),
('login.error.required', 'Nom d''utilisateur et mot de passe requis', 'fr'),
('login.error.required', 'Требуются имя пользователя и пароль', 'ru'),
('login.error.token', 'Failed to extract token from response', 'en'),
('login.error.token', 'استخراج توکن از پاسخ ناموفق بود', 'fa'),
('login.error.token', 'Impossible d''extraire le jeton de la réponse', 'fr'),
('login.error.token', 'Не удалось извлечь токен из ответа', 'ru'),
('login.error.failed', 'Login failed: {0}', 'en'),
('login.error.failed', 'ورود ناموفق: {0}', 'fa'),
('login.error.failed', 'Échec de la connexion : {0}', 'fr'),
('login.error.failed', 'Ошибка входа: {0}', 'ru'),
('login.error.connection', 'Connection error: {0}', 'en'),
('login.error.connection', 'خطای ارتباط: {0}', 'fa'),
('login.error.connection', 'Erreur de connexion : {0}', 'fr'),
('login.error.connection', 'Ошибка соединения: {0}', 'ru'),
('login.success.login', 'Login successful!', 'en'),
('login.success.login', 'ورود با موفقیت انجام شد!', 'fa'),
('login.success.login', 'Connexion réussie !', 'fr'),
('login.success.login', 'Вход выполнен успешно!', 'ru'),
('login.success.registration', 'Registration successful! Please log in.', 'en'),
('login.success.registration', 'ثبت نام با موفقیت انجام شد! لطفاً وارد شوید.', 'fa'),
('login.success.registration', 'Inscription réussie ! Veuillez vous connecter.', 'fr'),
('login.success.registration', 'Регистрация успешна! Пожалуйста, войдите.', 'ru'),
('login.error.username.exists', 'Username already exists', 'en'),
('login.error.username.exists', 'نام کاربری قبلاً وجود دارد', 'fa'),
('login.error.username.exists', 'Le nom d''utilisateur existe déjà', 'fr'),
('login.error.username.exists', 'Имя пользователя уже существует', 'ru'),
('login.error.registration.failed', 'Registration failed: {0}', 'en'),
('login.error.registration.failed', 'ثبت نام ناموفق: {0}', 'fa'),
('login.error.registration.failed', 'Échec de l''inscription : {0}', 'fr'),
('login.error.registration.failed', 'Ошибка регистрации: {0}', 'ru'),

-- Home Page
('home.welcome', 'Welcome, {0}!', 'en'),
('home.welcome', 'خوش آمدید، {0}!', 'fa'),
('home.welcome', 'Bienvenue, {0} !', 'fr'),
('home.welcome', 'Добро пожаловать, {0}!', 'ru'),
('home.subtitle', 'Here are your enrolled classes.', 'en'),
('home.subtitle', 'کلاس‌های ثبت‌شده شما در اینجا قرار دارند.', 'fa'),
('home.subtitle', 'Voici vos classes inscrites.', 'fr'),
('home.subtitle', 'Ваши записанные занятия.', 'ru'),
('home.manageClasses', '＋  Manage Classes', 'en'),
('home.manageClasses', '＋ مدیریت کلاس‌ها', 'fa'),
('home.manageClasses', '＋  Gérer les classes', 'fr'),
('home.manageClasses', '＋  Управление занятиями', 'ru'),
('home.joinClass', '  Join a Class', 'en'),
('home.joinClass', '  پیوستن به کلاس', 'fa'),
('home.joinClass', '  Rejoindre une classe', 'fr'),
('home.joinClass', '  Присоединиться к занятию', 'ru'),
('home.createClass', '  Create a Class', 'en'),
('home.createClass', '  ایجاد کلاس', 'fa'),
('home.createClass', '  Créer une classe', 'fr'),
('home.createClass', '  Создать занятие', 'ru'),
('home.loadingClasses', 'Loading your classes…', 'en'),
('home.loadingClasses', 'در حال بارگذاری کلاس‌ها…', 'fa'),
('home.loadingClasses', 'Chargement de vos classes…', 'fr'),
('home.loadingClasses', 'Загружаем ваши занятия…', 'ru'),
('home.noClasses', 'No classes yet. Ask your instructor to add you to a class!', 'en'),
('home.noClasses', 'هنوز کلاسی ندارید. از مدرس بخواهید شما را اضافه کند!', 'fa'),
('home.noClasses', 'Pas encore de cours. Demandez à votre instructeur de vous ajouter à une classe !', 'fr'),
('home.noClasses', 'Пока нет занятий. Попросите преподавателя добавить вас в класс!', 'ru'),
('home.openClass', 'Open Class →', 'en'),
('home.openClass', 'باز کردن کلاس →', 'fa'),
('home.openClass', 'Ouvrir la classe →', 'fr'),
('home.openClass', 'Открыть занятие →', 'ru'),
('home.noTopic', 'No topic set', 'en'),
('home.noTopic', 'موضوعی وجود ندارد', 'fa'),
('home.noTopic', 'Aucun sujet défini', 'fr'),
('home.noTopic', 'Тема не указана', 'ru'),
('home.joinClass.title', 'Join Class', 'en'),
('home.joinClass.title', 'پیوستن به کلاس', 'fa'),
('home.joinClass.title', 'Rejoindre la classe', 'fr'),
('home.joinClass.title', 'Присоединиться к занятию', 'ru'),
('home.joinClass.header', 'Enter Class ID to join', 'en'),
('home.joinClass.header', 'کد کلاس را وارد کنید', 'fa'),
('home.joinClass.header', 'Entrez l''identifiant de la classe', 'fr'),
('home.joinClass.header', 'Введите идентификатор занятия', 'ru'),
('home.joinClass.prompt', 'Enter class ID', 'en'),
('home.joinClass.prompt', 'کد کلاس را وارد کنید', 'fa'),
('home.joinClass.prompt', 'Entrez l''identifiant de la classe', 'fr'),
('home.joinClass.prompt', 'Введите идентификатор занятия', 'ru'),
('home.createClass.title', 'Create Class', 'en'),
('home.createClass.title', 'ایجاد کلاس', 'fa'),
('home.createClass.title', 'Créer une classe', 'fr'),
('home.createClass.title', 'Создать занятие', 'ru'),
('home.createClass.header', 'Create a new class', 'en'),
('home.createClass.header', 'یک کلاس جدید ایجاد کنید', 'fa'),
('home.createClass.header', 'Créer une nouvelle classe', 'fr'),
('home.createClass.header', 'Создайте новое занятие', 'ru'),
('home.createClass.nameLabel', 'Class Name:', 'en'),
('home.createClass.nameLabel', 'نام کلاس:', 'fa'),
('home.createClass.nameLabel', 'Nom de la classe :', 'fr'),
('home.createClass.nameLabel', 'Название занятия:', 'ru'),
('home.createClass.topicLabel', 'Topic:', 'en'),
('home.createClass.topicLabel', 'موضوع:', 'fa'),
('home.createClass.topicLabel', 'Sujet :', 'fr'),
('home.createClass.topicLabel', 'Тема:', 'ru'),
('home.createClass.namePrompt', 'Enter class name', 'en'),
('home.createClass.namePrompt', 'نام کلاس را وارد کنید', 'fa'),
('home.createClass.namePrompt', 'Entrez le nom de la classe', 'fr'),
('home.createClass.namePrompt', 'Введите название занятия', 'ru'),
('home.createClass.topicPrompt', 'Enter topic (optional)', 'en'),
('home.createClass.topicPrompt', 'موضوع را وارد کنید (اختیاری)', 'fa'),
('home.createClass.topicPrompt', 'Entrez le sujet (facultatif)', 'fr'),
('home.createClass.topicPrompt', 'Введите тему (необязательно)', 'ru'),
('home.createClass.success', 'Class created successfully!', 'en'),
('home.createClass.success', 'کلاس با موفقیت ایجاد شد!', 'fa'),
('home.createClass.success', 'Classe créée avec succès !', 'fr'),
('home.createClass.success', 'Занятие успешно создано!', 'ru'),
('home.success.title', 'Success', 'en'),
('home.success.title', 'موفقیت', 'fa'),
('home.success.title', 'Succès', 'fr'),
('home.success.title', 'Успех', 'ru'),
('home.error.title', 'Error', 'en'),
('home.error.title', 'خطا', 'fa'),
('home.error.title', 'Erreur', 'fr'),
('home.error.title', 'Ошибка', 'ru'),
('home.error.notAuthenticated', 'Error: Not authenticated', 'en'),
('home.error.notAuthenticated', 'خطا: احراز هویت نشده', 'fa'),
('home.error.notAuthenticated', 'Erreur: Non authentifié', 'fr'),
('home.error.notAuthenticated', 'Ошибка: не аутентифицирован', 'ru'),
('home.error.fetchUser', 'Error: Could not fetch user information', 'en'),
('home.error.fetchUser', 'خطا: نمی‌توان اطلاعات کاربر را دریافت کرد', 'fa'),
('home.error.fetchUser', 'Erreur: impossible de récupérer les informations utilisateur', 'fr'),
('home.error.fetchUser', 'Ошибка: не удалось получить информацию пользователя', 'ru'),
('home.error.loadingClasses', 'Error loading classes: {0}', 'en'),
('home.error.loadingClasses', 'خطا در بارگذاری کلاس‌ها: {0}', 'fa'),
('home.error.loadingClasses', 'Erreur lors du chargement des classes: {0}', 'fr'),
('home.error.loadingClasses', 'Ошибка при загрузке занятий: {0}', 'ru'),
('home.error.createClass', 'Failed to create class: {0}', 'en'),
('home.error.createClass', 'خطا در ایجاد کلاس: {0}', 'fa'),
('home.error.createClass', 'Échec de la création de la classe: {0}', 'fr'),
('home.error.createClass', 'Ошибка при создании занятия: {0}', 'ru'),
('home.error.createClassException', 'Failed to create class: {0}', 'en'),
('home.error.createClassException', 'خطا در ایجاد کلاس: {0}', 'fa'),
('home.error.createClassException', 'Échec de la création de la classe: {0}', 'fr'),
('home.error.createClassException', 'Ошибка при создании занятия: {0}', 'ru'),

-- Profile Page
('profile.title', 'My Profile', 'en'),
('profile.title', 'پروفایل من', 'fa'),
('profile.title', 'Mon profil', 'fr'),
('profile.title', 'Мой профиль', 'ru'),
('profile.subtitle', 'Manage your account and settings', 'en'),
('profile.subtitle', 'حساب و تنظیمات خود را مدیریت کنید', 'fa'),
('profile.subtitle', 'Gérez votre compte et vos paramètres', 'fr'),
('profile.subtitle', 'Управляйте своей учетной записью и параметрами', 'ru'),
('profile.back', '← Back to Home', 'en'),
('profile.back', '← بازگشت به خانه', 'fa'),
('profile.back', '← Retour à l''accueil', 'fr'),
('profile.back', '← Вернуться на главную', 'ru'),
('profile.loading', 'Loading...', 'en'),
('profile.loading', 'در حال بارگذاری...', 'fa'),
('profile.loading', 'Chargement...', 'fr'),
('profile.loading', 'Загрузка...', 'ru'),
('profile.username', 'Username', 'en'),
('profile.username', 'نام کاربری', 'fa'),
('profile.username', 'Nom d''utilisateur', 'fr'),
('profile.username', 'Имя пользователя', 'ru'),
('profile.email', 'Email', 'en'),
('profile.email', 'ایمیل', 'fa'),
('profile.email', 'E-mail', 'fr'),
('profile.email', 'Эл. почта', 'ru'),
('profile.changePassword', 'Change Password', 'en'),
('profile.changePassword', 'تغییر رمز عبور', 'fa'),
('profile.changePassword', 'Changer le mot de passe', 'fr'),
('profile.changePassword', 'Изменить пароль', 'ru'),
('profile.currentPassword', 'Current Password', 'en'),
('profile.currentPassword', 'رمز عبور فعلی', 'fa'),
('profile.currentPassword', 'Mot de passe actuel', 'fr'),
('profile.currentPassword', 'Текущий пароль', 'ru'),
('profile.currentPassword.prompt', 'Enter current password', 'en'),
('profile.currentPassword.prompt', 'رمز عبور فعلی را وارد کنید', 'fa'),
('profile.currentPassword.prompt', 'Entrez le mot de passe actuel', 'fr'),
('profile.currentPassword.prompt', 'Введите текущий пароль', 'ru'),
('profile.newPassword', 'New Password', 'en'),
('profile.newPassword', 'رمز عبور جدید', 'fa'),
('profile.newPassword', 'Nouveau mot de passe', 'fr'),
('profile.newPassword', 'Новый пароль', 'ru'),
('profile.newPassword.prompt', 'Enter new password', 'en'),
('profile.newPassword.prompt', 'رمز عبور جدید را وارد کنید', 'fa'),
('profile.newPassword.prompt', 'Entrez le nouveau mot de passe', 'fr'),
('profile.newPassword.prompt', 'Введите новый пароль', 'ru'),
('profile.confirmNewPassword', 'Confirm New Password', 'en'),
('profile.confirmNewPassword', 'تأیید رمز عبور جدید', 'fa'),
('profile.confirmNewPassword', 'Confirmer le nouveau mot de passe', 'fr'),
('profile.confirmNewPassword', 'Подтвердите новый пароль', 'ru'),
('profile.confirmNewPassword.prompt', 'Confirm new password', 'en'),
('profile.confirmNewPassword.prompt', 'رمز عبور جدید را تأیید کنید', 'fa'),
('profile.confirmNewPassword.prompt', 'Confirmez le nouveau mot de passe', 'fr'),
('profile.confirmNewPassword.prompt', 'Подтвердите новый пароль', 'ru'),
('profile.logout', 'Logout', 'en'),
('profile.logout', 'خروج', 'fa'),
('profile.logout', 'Déconnexion', 'fr'),
('profile.logout', 'Выйти', 'ru'),
('profile.unknown', 'Unknown', 'en'),
('profile.unknown', 'نامشخص', 'fa'),
('profile.unknown', 'Inconnu', 'fr'),
('profile.unknown', 'Неизвестно', 'ru'),
('profile.success.passwordChanged', 'Password changed successfully!', 'en'),
('profile.success.passwordChanged', 'رمز عبور با موفقیت تغییر کرد!', 'fa'),
('profile.success.passwordChanged', 'Mot de passe changé avec succès !', 'fr'),
('profile.success.passwordChanged', 'Пароль успешно изменен!', 'ru'),
('profile.error.title', 'Error', 'en'),
('profile.error.title', 'خطا', 'fa'),
('profile.error.title', 'Erreur', 'fr'),
('profile.error.title', 'Ошибка', 'ru'),
('profile.error.currentPasswordRequired', 'Current password is required', 'en'),
('profile.error.currentPasswordRequired', 'رمز عبور فعلی الزامی است', 'fa'),
('profile.error.currentPasswordRequired', 'Le mot de passe actuel est requis', 'fr'),
('profile.error.currentPasswordRequired', 'Требуется текущий пароль', 'ru'),
('profile.error.newPasswordRequired', 'New password is required', 'en'),
('profile.error.newPasswordRequired', 'رمز عبور جدید الزامی است', 'fa'),
('profile.error.newPasswordRequired', 'Le nouveau mot de passe est requis', 'fr'),
('profile.error.newPasswordRequired', 'Требуется новый пароль', 'ru'),
('profile.error.confirmPasswordRequired', 'Confirm password is required', 'en'),
('profile.error.confirmPasswordRequired', 'تأیید رمز عبور الزامی است', 'fa'),
('profile.error.confirmPasswordRequired', 'La confirmation du mot de passe est requise', 'fr'),
('profile.error.confirmPasswordRequired', 'Требуется подтверждение пароля', 'ru'),
('profile.error.passwordMismatch', 'Passwords do not match', 'en'),
('profile.error.passwordMismatch', 'رمزهای عبور مطابقت ندارند', 'fa'),
('profile.error.passwordMismatch', 'Les mots de passe ne correspondent pas', 'fr'),
('profile.error.passwordMismatch', 'Пароли не совпадают', 'ru'),
('profile.error.passwordDifferent', 'New password must be different from current password', 'en'),
('profile.error.passwordDifferent', 'رمز عبور جدید باید متفاوت از رمز فعلی باشد', 'fa'),
('profile.error.passwordDifferent', 'Le nouveau mot de passe doit être différent du mot de passe actuel', 'fr'),
('profile.error.passwordDifferent', 'Новый пароль должен отличаться от текущего', 'ru'),
('profile.error.passwordMinLength', 'Password must be at least 6 characters', 'en'),
('profile.error.passwordMinLength', 'رمز عبور باید حداقل ۶ حرف باشد', 'fa'),
('profile.error.passwordMinLength', 'Le mot de passe doit contenir au moins 6 caractères', 'fr'),
('profile.error.passwordMinLength', 'Пароль должен содержать минимум 6 символов', 'ru'),
('profile.error.currentPasswordIncorrect', 'Current password is incorrect', 'en'),
('profile.error.currentPasswordIncorrect', 'رمز عبور فعلی نادرست است', 'fa'),
('profile.error.currentPasswordIncorrect', 'Le mot de passe actuel est incorrect', 'fr'),
('profile.error.currentPasswordIncorrect', 'Текущий пароль неправильный', 'ru'),
('profile.error.passwordChangeFailed', 'Failed to change password: {0}', 'en'),
('profile.error.passwordChangeFailed', 'تغییر رمز عبور ناموفق: {0}', 'fa'),
('profile.error.passwordChangeFailed', 'Impossible de changer le mot de passe: {0}', 'fr'),
('profile.error.passwordChangeFailed', 'Ошибка при изменении пароля: {0}', 'ru'),
('profile.error.connection', 'Connection error: {0}', 'en'),
('profile.error.connection', 'خطای اتصال: {0}', 'fa'),
('profile.error.connection', 'Erreur de connexion: {0}', 'fr'),
('profile.error.connection', 'Ошибка соединения: {0}', 'ru'),

-- Register Page
('register.title', 'Create Account', 'en'),
('register.title', 'ایجاد حساب', 'fa'),
('register.title', 'Créer un compte', 'fr'),
('register.title', 'Создать аккаунт', 'ru'),
('register.subtitle', 'Join our learning platform', 'en'),
('register.subtitle', 'به پلتفرم یادگیری ما بپیوندید', 'fa'),
('register.subtitle', 'Rejoignez notre plateforme d''apprentissage', 'fr'),
('register.subtitle', 'Присоединитесь к нашей платформе обучения', 'ru'),
('register.username', 'Username', 'en'),
('register.username', 'نام کاربری', 'fa'),
('register.username', 'Nom d''utilisateur', 'fr'),
('register.username', 'Имя пользователя', 'ru'),
('register.username.prompt', 'Enter your username', 'en'),
('register.username.prompt', 'نام کاربری خود را وارد کنید', 'fa'),
('register.username.prompt', 'Entrez votre nom d''utilisateur', 'fr'),
('register.username.prompt', 'Введите ваше имя пользователя', 'ru'),
('register.email', 'Email Address', 'en'),
('register.email', 'آدرس ایمیل', 'fa'),
('register.email', 'Adresse e-mail', 'fr'),
('register.email', 'Адрес электронной почты', 'ru'),
('register.email.prompt', 'Enter your email', 'en'),
('register.email.prompt', 'ایمیل خود را وارد کنید', 'fa'),
('register.email.prompt', 'Entrez votre e-mail', 'fr'),
('register.email.prompt', 'Введите ваш e-mail', 'ru'),
('register.password', 'Password', 'en'),
('register.password', 'رمز عبور', 'fa'),
('register.password', 'Mot de passe', 'fr'),
('register.password', 'Пароль', 'ru'),
('register.password.prompt', 'Enter password (min 6 characters)', 'en'),
('register.password.prompt', 'رمز عبور را وارد کنید (حداقل ۶ حرف)', 'fa'),
('register.password.prompt', 'Entrez un mot de passe (min 6 caractères)', 'fr'),
('register.password.prompt', 'Введите пароль (минимум 6 символов)', 'ru'),
('register.confirmPassword', 'Confirm Password', 'en'),
('register.confirmPassword', 'تأیید رمز عبور', 'fa'),
('register.confirmPassword', 'Confirmer le mot de passe', 'fr'),
('register.confirmPassword', 'Подтвердите пароль', 'ru'),
('register.confirmPassword.prompt', 'Confirm your password', 'en'),
('register.confirmPassword.prompt', 'رمز عبور خود را تأیید کنید', 'fa'),
('register.confirmPassword.prompt', 'Confirmez votre mot de passe', 'fr'),
('register.confirmPassword.prompt', 'Подтвердите ваш пароль', 'ru'),
('register.createAccount', 'Create Account', 'en'),
('register.createAccount', 'ایجاد حساب', 'fa'),
('register.createAccount', 'Créer un compte', 'fr'),
('register.createAccount', 'Создать аккаунт', 'ru'),
('register.alreadyAccount', 'Already have an account?', 'en'),
('register.alreadyAccount', 'آیا قبلاً حساب دارید؟', 'fa'),
('register.alreadyAccount', 'Vous avez déjà un compte ?', 'fr'),
('register.alreadyAccount', 'Уже есть аккаунт?', 'ru'),
('register.signIn', 'Sign In', 'en'),
('register.signIn', 'ورود', 'fa'),
('register.signIn', 'Se connecter', 'fr'),
('register.signIn', 'Войти', 'ru'),

-- Class Details
('class.back', '← Back', 'en'),
('class.back', '← بازگشت', 'fa'),
('class.back', '← Retour', 'fr'),
('class.back', '← Назад', 'ru'),
('class.joinClass', 'Join Class', 'en'),
('class.joinClass', 'پیوستن به کلاس', 'fa'),
('class.joinClass', 'Rejoindre la classe', 'fr'),
('class.joinClass', 'Присоединиться к занятию', 'ru'),
('class.refresh', '↻  Refresh', 'en'),
('class.refresh', '↻ تازه‌کنی', 'fa'),
('class.refresh', '↻  Actualiser', 'fr'),
('class.refresh', '↻  Обновить', 'ru'),
('class.leaveClass', 'Leave Class', 'en'),
('class.leaveClass', 'ترک کلاس', 'fa'),
('class.leaveClass', 'Quitter la classe', 'fr'),
('class.leaveClass', 'Покинуть занятие', 'ru'),
('class.deleteClass', '  Delete Class', 'en'),
('class.deleteClass', '  حذف کلاس', 'fa'),
('class.deleteClass', '  Supprimer la classe', 'fr'),
('class.deleteClass', '  Удалить занятие', 'ru'),
('class.delete', 'Delete', 'en'),
('class.delete', 'حذف', 'fa'),
('class.delete', 'Supprimer', 'fr'),
('class.delete', 'Удалить', 'ru'),
('class.download', '⬇ Download', 'en'),
('class.download', '⬇ دانلود', 'fa'),
('class.download', '⬇ Télécharger', 'fr'),
('class.download', '⬇ Скачать', 'ru'),
('class.reviews', 'Reviews', 'en'),
('class.reviews', 'بررسی‌ها', 'fa'),
('class.reviews', 'Avis', 'fr'),
('class.reviews', 'Отзывы', 'ru'),
('class.review', 'Review', 'en'),
('class.review', 'بررسی', 'fa'),
('class.review', 'Avis', 'fr'),
('class.review', 'Оценить', 'ru'),
('class.noFilesUploadedYet', 'No files uploaded yet.', 'en'),
('class.noFilesUploadedYet', 'هنوز فایلی آپلود نشده است.', 'fa'),
('class.noFilesUploadedYet', 'Aucun fichier téléchargé pour le moment.', 'fr'),
('class.noFilesUploadedYet', 'Файлы пока не загружены.', 'ru'),
('class.filesAvailable', '{0} file(s) available', 'en'),
('class.filesAvailable', '{0} فایل موجود', 'fa'),
('class.filesAvailable', '{0} fichier(s) disponible(s)', 'fr'),
('class.filesAvailable', '{0} файлов доступно', 'ru'),
('class.uploadedByUser', 'Uploaded by user #{0}', 'en'),
('class.uploadedByUser', 'آپلود شده توسط کاربر #{0}', 'fa'),
('class.uploadedByUser', 'Téléchargé par l''utilisateur #{0}', 'fr'),
('class.uploadedByUser', 'Загружено пользователем #{0}', 'ru'),
('class.uploaderUnknown', 'Uploader unknown', 'en'),
('class.uploaderUnknown', 'آپلودکننده نامشخص', 'fa'),
('class.uploaderUnknown', 'Téléchargeur inconnu', 'fr'),
('class.uploaderUnknown', 'Загружающий неизвестен', 'ru'),
('class.error.title', 'Error', 'en'),
('class.error.title', 'خطا', 'fa'),
('class.error.title', 'Erreur', 'fr'),
('class.error.title', 'Ошибка', 'ru'),
('class.error.loadDetails', 'Failed to load class details', 'en'),
('class.error.loadDetails', 'خطا در بارگذاری جزئیات کلاس', 'fa'),
('class.error.loadDetails', 'Échec du chargement des détails de la classe', 'fr'),
('class.error.loadDetails', 'Ошибка при загрузке информации о занятии', 'ru'),
('class.classId', 'Class ID: {0}', 'en'),
('class.classId', 'کد کلاس: {0}', 'fa'),
('class.classId', 'ID de classe: {0}', 'fr'),
('class.classId', 'Код занятия: {0}', 'ru'),
('class.topic', 'Topic: {0}', 'en'),
('class.topic', 'موضوع: {0}', 'fa'),
('class.topic', 'Sujet: {0}', 'fr'),
('class.topic', 'Тема: {0}', 'ru'),
('class.creator', 'Created by: User #{0}', 'en'),
('class.creator', 'ایجاد شده توسط: کاربر #{0}', 'fa'),
('class.creator', 'Créé par: Utilisateur #{0}', 'fr'),
('class.creator', 'Создано пользователем: #{0}', 'ru'),
('class.creatorUnknown', 'Unknown', 'en'),
('class.creatorUnknown', 'نامشخص', 'fa'),
('class.creatorUnknown', 'Inconnu', 'fr'),
('class.creatorUnknown', 'Неизвестно', 'ru'),
('class.unknown', 'Unknown class', 'en'),
('class.unknown', 'کلاس نامشخص', 'fa'),
('class.unknown', 'Classe inconnue', 'fr'),
('class.unknown', 'Неизвестный класс', 'ru'),
('class.noTopic', 'No topic', 'en'),
('class.noTopic', 'بدون موضوع', 'fa'),
('class.noTopic', 'Pas de sujet', 'fr'),
('class.noTopic', 'Нет темы', 'ru'),
('class.uploadTitle', '  Upload Class Material', 'en'),
('class.uploadTitle', '  آپلود محتوای کلاس', 'fa'),
('class.uploadTitle', '  Téléverser le matériel de la classe', 'fr'),
('class.uploadTitle', '  Загрузить материал занятия', 'ru'),
('class.uploadSubtitle', 'Upload documents, assignments, and references for your students.', 'en'),
('class.uploadSubtitle', 'اسناد، تکالیف و منابع را برای دانشجویان خود بارگذاری کنید.', 'fa'),
('class.uploadSubtitle', 'Téléversez des documents, des devoirs et des références pour vos étudiants.', 'fr'),
('class.uploadSubtitle', 'Загружайте документы, задания и справочные материалы для ваших студентов.', 'ru'),
('class.upload', 'Upload', 'en'),
('class.upload', 'آپلود', 'fa'),
('class.upload', 'Téléverser', 'fr'),
('class.upload', 'Загрузить', 'ru'),
('class.materialType.prompt', 'Select material type', 'en'),
('class.materialType.prompt', 'نوع محتوا را انتخاب کنید', 'fa'),
('class.materialType.prompt', 'Sélectionner le type de matériel', 'fr'),
('class.materialType.prompt', 'Выберите тип материала', 'ru'),
('class.materialType.lectureNotes', 'Lecture Notes', 'en'),
('class.materialType.lectureNotes', 'جزوه درسی', 'fa'),
('class.materialType.lectureNotes', 'Notes de cours', 'fr'),
('class.materialType.lectureNotes', 'Конспект лекции', 'ru'),
('class.materialType.assignment', 'Assignment', 'en'),
('class.materialType.assignment', 'تکلیف', 'fa'),
('class.materialType.assignment', 'Devoir', 'fr'),
('class.materialType.assignment', 'Задание', 'ru'),
('class.materialType.slides', 'Slides', 'en'),
('class.materialType.slides', 'اسلایدها', 'fa'),
('class.materialType.slides', 'Diapositives', 'fr'),
('class.materialType.slides', 'Слайды', 'ru'),
('class.materialType.reference', 'Reference', 'en'),
('class.materialType.reference', 'منبع', 'fa'),
('class.materialType.reference', 'Référence', 'fr'),
('class.materialType.reference', 'Справочный материал', 'ru'),
('class.materialType.other', 'Other', 'en'),
('class.materialType.other', 'سایر', 'fa'),
('class.materialType.other', 'Autre', 'fr'),
('class.materialType.other', 'Другое', 'ru'),
('class.couldNotLoadFiles', 'Could not load files right now.', 'en'),
('class.couldNotLoadFiles', 'نمی‌توان اکنون فایل‌ها را بارگذاری کرد.', 'fa'),
('class.couldNotLoadFiles', 'Impossible de charger les fichiers maintenant.', 'fr'),
('class.couldNotLoadFiles', 'Не удалось загрузить файлы прямо сейчас.', 'ru'),
('class.couldNotLoadFilesShort', 'Could not load files.', 'en'),
('class.couldNotLoadFilesShort', 'نمی‌توان فایل‌ها را بارگذاری کرد.', 'fa'),
('class.couldNotLoadFilesShort', 'Impossible de charger les fichiers.', 'fr'),
('class.couldNotLoadFilesShort', 'Не удалось загрузить файлы.', 'ru'),
('class.loadingFiles', 'Loading files…', 'en'),
('class.loadingFiles', 'بارگذاری فایل‌ها…', 'fa'),
('class.loadingFiles', 'Chargement des fichiers…', 'fr'),
('class.loadingFiles', 'Загрузка файлов…', 'ru'),
('class.error.missingId', 'Class ID not provided', 'en'),
('class.error.missingId', 'کد کلاس ارائه نشده', 'fa'),
('class.error.missingId', 'Identifiant de classe non fourni', 'fr'),
('class.error.missingId', 'Код занятия не указан', 'ru'),
('class.actions', 'Actions', 'en'),
('class.actions', 'عملیات', 'fa'),
('class.actions', 'Actions', 'fr'),
('class.actions', 'Действия', 'ru'),
('class.chooseFile', 'Choose File', 'en'),
('class.chooseFile', 'انتخاب فایل', 'fa'),
('class.chooseFile', 'Choisir un fichier', 'fr'),
('class.chooseFile', 'Выбрать файл', 'ru'),
('class.noFileSelected', 'No file selected', 'en'),
('class.noFileSelected', 'فایلی انتخاب نشده است', 'fa'),
('class.noFileSelected', 'Aucun fichier sélectionné', 'fr'),
('class.noFileSelected', 'Файл не выбран', 'ru'),
('class.materialsTitle', 'Class Materials', 'en'),
('class.materialsTitle', 'محتوای کلاس', 'fa'),
('class.materialsTitle', 'Matériel de la classe', 'fr'),
('class.materialsTitle', 'Материалы занятия', 'ru'),
('class.classCreator', 'Class Creator', 'en'),
('class.classCreator', 'مدرس کلاس', 'fa'),
('class.classCreator', 'Créateur de la classe', 'fr'),
('class.classCreator', 'Создатель занятия', 'ru'),
('class.alreadyEnrolled', 'Already Enrolled', 'en'),
('class.alreadyEnrolled', 'قبلا ثبت‌نام شده', 'fa'),
('class.alreadyEnrolled', 'Déjà inscrit', 'fr'),
('class.alreadyEnrolled', 'Уже записан', 'ru'),
('class.joinToAccess', 'Join this class to access materials.', 'en'),
('class.joinToAccess', 'برای دسترسی به محتوا در این کلاس عضو شوید.', 'fa'),
('class.joinToAccess', 'Rejoignez cette classe pour accéder aux contenus.', 'fr'),
('class.joinToAccess', 'Присоединитесь к занятию, чтобы получить доступ к материалам.', 'ru'),
('class.unnamedFile', 'Unnamed file', 'en'),
('class.unnamedFile', 'فایل بدون نام', 'fa'),
('class.unnamedFile', 'Fichier sans nom', 'fr'),
('class.unnamedFile', 'Файл без имени', 'ru'),
('class.unknownDate', 'Unknown date', 'en'),
('class.unknownDate', 'تاریخ نامشخص', 'fa'),
('class.unknownDate', 'Date inconnue', 'fr'),
('class.unknownDate', 'Неизвестная дата', 'ru'),
('class.reviewer', 'User #{0}', 'en'),
('class.reviewer', 'کاربر #{0}', 'fa'),
('class.reviewer', 'Utilisateur #{0}', 'fr'),
('class.reviewer', 'Пользователь #{0}', 'ru'),
('class.unknownUser', 'Unknown user', 'en'),
('class.unknownUser', 'کاربر ناشناس', 'fa'),
('class.unknownUser', 'Utilisateur inconnu', 'fr'),
('class.unknownUser', 'Неизвестный пользователь', 'ru'),
('class.noComment', 'No comment', 'en'),
('class.noComment', 'بدون نظر', 'fa'),
('class.noComment', 'Aucun commentaire', 'fr'),
('class.noComment', 'Без комментария', 'ru'),
('class.reviewLine', 'Rating: {0}/5 - {1}: {2}', 'en'),
('class.reviewLine', 'امتیاز: {0}/5 - {1}: {2}', 'fa'),
('class.reviewLine', 'Note: {0}/5 - {1} : {2}', 'fr'),
('class.reviewLine', 'Оценка: {0}/5 - {1}: {2}', 'ru'),
('class.noReviewsYet', 'No reviews yet.', 'en'),
('class.noReviewsYet', 'هنوز نظری ثبت نشده است.', 'fa'),
('class.noReviewsYet', 'Aucun avis pour le moment.', 'fr'),
('class.noReviewsYet', 'Пока нет отзывов.', 'ru'),
('class.reviewCount', '{0} review(s)', 'en'),
('class.reviewCount', '{0} نظر', 'fa'),
('class.reviewCount', '{0} avis', 'fr'),
('class.reviewCount', '{0} отзыв(ов)', 'ru'),
('class.dialog.selectMaterialFile', 'Select material file', 'en'),
('class.dialog.selectMaterialFile', 'انتخاب فایل محتوا', 'fa'),
('class.dialog.selectMaterialFile', 'Sélectionner un fichier de matériel', 'fr'),
('class.dialog.selectMaterialFile', 'Выберите файл материала', 'ru'),
('class.dialog.saveMaterial', 'Save material as', 'en'),
('class.dialog.saveMaterial', 'ذخیره فایل محتوا', 'fa'),
('class.dialog.saveMaterial', 'Enregistrer le matériel sous', 'fr'),
('class.dialog.saveMaterial', 'Сохранить материал как', 'ru'),
('class.status.uploadingFile', 'Uploading {0}...', 'en'),
('class.status.uploadingFile', 'در حال آپلود {0}...', 'fa'),
('class.status.uploadingFile', 'Téléversement de {0}...', 'fr'),
('class.status.uploadingFile', 'Загрузка {0}...', 'ru'),
('class.status.downloading', 'Downloading...', 'en'),
('class.status.downloading', 'در حال دانلود...', 'fa'),
('class.status.downloading', 'Téléchargement...', 'fr'),
('class.status.downloading', 'Загрузка...', 'ru'),
('class.status.deleting', 'Deleting...', 'en'),
('class.status.deleting', 'در حال حذف...', 'fa'),
('class.status.deleting', 'Suppression...', 'fr'),
('class.status.deleting', 'Удаление...', 'ru'),
('class.status.submittingReview', 'Submitting review...', 'en'),
('class.status.submittingReview', 'در حال ارسال نظر...', 'fa'),
('class.status.submittingReview', 'Envoi de l''avis...', 'fr'),
('class.status.submittingReview', 'Отправка отзыва...', 'ru'),
('class.success.uploaded', 'Material uploaded successfully.', 'en'),
('class.success.uploaded', 'محتوا با موفقیت آپلود شد.', 'fa'),
('class.success.uploaded', 'Le matériel a été téléversé avec succès.', 'fr'),
('class.success.uploaded', 'Материал успешно загружен.', 'ru'),
('class.success.deleted', 'Deleted: {0}', 'en'),
('class.success.deleted', 'حذف شد: {0}', 'fa'),
('class.success.deleted', 'Supprimé : {0}', 'fr'),
('class.success.deleted', 'Удалено: {0}', 'ru'),
('class.success.downloadComplete', 'Download complete', 'en'),
('class.success.downloadComplete', 'دانلود کامل شد', 'fa'),
('class.success.downloadComplete', 'Téléchargement terminé', 'fr'),
('class.success.downloadComplete', 'Загрузка завершена', 'ru'),
('class.success.downloadSaved', 'Saved to: {0}', 'en'),
('class.success.downloadSaved', 'ذخیره شد در: {0}', 'fa'),
('class.success.downloadSaved', 'Enregistré dans : {0}', 'fr'),
('class.success.downloadSaved', 'Сохранено в: {0}', 'ru'),
('class.success.reviewSubmitted', 'Review submitted successfully.', 'en'),
('class.success.reviewSubmitted', 'نظر با موفقیت ارسال شد.', 'fa'),
('class.success.reviewSubmitted', 'Avis envoyé avec succès.', 'fr'),
('class.success.reviewSubmitted', 'Отзыв успешно отправлен.', 'ru'),
('class.success.joined', 'Joined class successfully.', 'en'),
('class.success.joined', 'با موفقیت به کلاس پیوستید.', 'fa'),
('class.success.joined', 'Classe rejointe avec succès.', 'fr'),
('class.success.joined', 'Вы успешно присоединились к занятию.', 'ru'),
('class.success.leftClass', 'Left class successfully.', 'en'),
('class.success.leftClass', 'با موفقیت از کلاس خارج شدید.', 'fa'),
('class.success.leftClass', 'Vous avez quitté la classe avec succès.', 'fr'),
('class.success.leftClass', 'Вы успешно покинули занятие.', 'ru'),
('class.success.classDeleted', 'Class deleted successfully.', 'en'),
('class.success.classDeleted', 'کلاس با موفقیت حذف شد.', 'fa'),
('class.success.classDeleted', 'Classe supprimée avec succès.', 'fr'),
('class.success.classDeleted', 'Занятие успешно удалено.', 'ru'),
('class.error.serverResponse', 'Server responded with status {0}.', 'en'),
('class.error.serverResponse', 'سرور با وضعیت {0} پاسخ داد.', 'fa'),
('class.error.serverResponse', 'Le serveur a répondu avec le statut {0}.', 'fr'),
('class.error.serverResponse', 'Сервер ответил со статусом {0}.', 'ru'),
('class.error.failedLoad', 'Failed to load class details: {0}', 'en'),
('class.error.failedLoad', 'بارگذاری جزئیات کلاس ناموفق بود: {0}', 'fa'),
('class.error.failedLoad', 'Échec du chargement des détails de la classe : {0}', 'fr'),
('class.error.failedLoad', 'Не удалось загрузить данные занятия: {0}', 'ru'),
('class.error.onlyCreatorUpload', 'Only the class creator can upload materials.', 'en'),
('class.error.onlyCreatorUpload', 'فقط سازنده کلاس می‌تواند محتوا آپلود کند.', 'fa'),
('class.error.onlyCreatorUpload', 'Seul le créateur de la classe peut téléverser du matériel.', 'fr'),
('class.error.onlyCreatorUpload', 'Только создатель занятия может загружать материалы.', 'ru'),
('class.error.missingFile', 'Please select a file first.', 'en'),
('class.error.missingFile', 'لطفا ابتدا یک فایل انتخاب کنید.', 'fa'),
('class.error.missingFile', 'Veuillez d''abord sélectionner un fichier.', 'fr'),
('class.error.missingFile', 'Сначала выберите файл.', 'ru'),
('class.error.missingType', 'Please select a material type.', 'en'),
('class.error.missingType', 'لطفا نوع محتوا را انتخاب کنید.', 'fa'),
('class.error.missingType', 'Veuillez sélectionner un type de matériel.', 'fr'),
('class.error.missingType', 'Выберите тип материала.', 'ru'),
('class.error.uploadFailed', 'Upload failed', 'en'),
('class.error.uploadFailed', 'آپلود ناموفق بود', 'fa'),
('class.error.uploadFailed', 'Échec du téléversement', 'fr'),
('class.error.uploadFailed', 'Ошибка загрузки', 'ru'),
('class.error.downloadFailed', 'Download failed', 'en'),
('class.error.downloadFailed', 'دانلود ناموفق بود', 'fa'),
('class.error.downloadFailed', 'Échec du téléchargement', 'fr'),
('class.error.downloadFailed', 'Ошибка скачивания', 'ru'),
('class.error.deleteFailed', 'Delete failed', 'en'),
('class.error.deleteFailed', 'حذف ناموفق بود', 'fa'),
('class.error.deleteFailed', 'Échec de la suppression', 'fr'),
('class.error.deleteFailed', 'Удаление не удалось', 'ru'),
('class.error.reviews.title', 'Reviews Error', 'en'),
('class.error.reviews.title', 'خطای بررسی‌ها', 'fa'),
('class.error.reviews.title', 'Erreur des avis', 'fr'),
('class.error.reviews.title', 'Ошибка отзывов', 'ru'),
('class.error.openReviews', 'Could not open reviews dialog: {0}', 'en'),
('class.error.openReviews', 'باز کردن پنجره بررسی‌ها ممکن نشد: {0}', 'fa'),
('class.error.openReviews', 'Impossible d''ouvrir la fenêtre des avis : {0}', 'fr'),
('class.error.openReviews', 'Не удалось открыть окно отзывов: {0}', 'ru'),
('class.error.reviewListUnavailable', 'Review service is currently unavailable.', 'en'),
('class.error.reviewListUnavailable', 'سرویس بررسی‌ها در حال حاضر در دسترس نیست.', 'fa'),
('class.error.reviewListUnavailable', 'Le service d''avis est actuellement indisponible.', 'fr'),
('class.error.reviewListUnavailable', 'Сервис отзывов сейчас недоступен.', 'ru'),
('class.error.reviewsWithCode', 'Could not load reviews ({0}).', 'en'),
('class.error.reviewsWithCode', 'بارگذاری بررسی‌ها ممکن نشد ({0}).', 'fa'),
('class.error.reviewsWithCode', 'Impossible de charger les avis ({0}).', 'fr'),
('class.error.reviewsWithCode', 'Не удалось загрузить отзывы ({0}).', 'ru'),
('class.error.review.title', 'Review Error', 'en'),
('class.error.review.title', 'خطای ارسال نظر', 'fa'),
('class.error.review.title', 'Erreur d''avis', 'fr'),
('class.error.review.title', 'Ошибка отзыва', 'ru'),
('class.error.openReviewForm', 'Could not open review form: {0}', 'en'),
('class.error.openReviewForm', 'باز کردن فرم نظر ممکن نشد: {0}', 'fa'),
('class.error.openReviewForm', 'Impossible d''ouvrir le formulaire d''avis : {0}', 'fr'),
('class.error.openReviewForm', 'Не удалось открыть форму отзыва: {0}', 'ru'),
('class.error.forbiddenReview', 'Class creator cannot submit reviews for own materials.', 'en'),
('class.error.forbiddenReview', 'سازنده کلاس نمی‌تواند برای محتوای خودش نظر ثبت کند.', 'fa'),
('class.error.forbiddenReview', 'Le créateur de la classe ne peut pas évaluer ses propres contenus.', 'fr'),
('class.error.forbiddenReview', 'Создатель занятия не может оценивать собственные материалы.', 'ru'),
('class.error.invalidRating', 'Please select a rating between 1 and 5.', 'en'),
('class.error.invalidRating', 'لطفا امتیاز بین 1 تا 5 را انتخاب کنید.', 'fa'),
('class.error.invalidRating', 'Veuillez sélectionner une note entre 1 et 5.', 'fr'),
('class.error.invalidRating', 'Выберите оценку от 1 до 5.', 'ru'),
('class.error.invalidComment', 'Comment must be 1 to {0} characters.', 'en'),
('class.error.invalidComment', 'نظر باید بین 1 تا {0} کاراکتر باشد.', 'fa'),
('class.error.invalidComment', 'Le commentaire doit contenir entre 1 et {0} caractères.', 'fr'),
('class.error.invalidComment', 'Комментарий должен быть длиной от 1 до {0} символов.', 'ru'),
('class.error.reviewFailed', 'Review submission failed', 'en'),
('class.error.reviewFailed', 'ارسال نظر ناموفق بود', 'fa'),
('class.error.reviewFailed', 'Échec de l''envoi de l''avis', 'fr'),
('class.error.reviewFailed', 'Не удалось отправить отзыв', 'ru'),
('class.error.reviewSubmitWithCode', 'Could not submit review right now ({0}).', 'en'),
('class.error.reviewSubmitWithCode', 'در حال حاضر امکان ارسال نظر نیست ({0}).', 'fa'),
('class.error.reviewSubmitWithCode', 'Impossible d''envoyer l''avis pour le moment ({0}).', 'fr'),
('class.error.reviewSubmitWithCode', 'Сейчас не удалось отправить отзыв ({0}).', 'ru'),
('class.error.reviewApiUnavailable', 'Review API unavailable. Details: {0}', 'en'),
('class.error.reviewApiUnavailable', 'API بررسی‌ها در دسترس نیست. جزئیات: {0}', 'fa'),
('class.error.reviewApiUnavailable', 'API des avis indisponible. Détails : {0}', 'fr'),
('class.error.reviewApiUnavailable', 'API отзывов недоступен. Детали: {0}', 'ru'),
('class.error.joinFailed', 'Failed to join class ({0}).', 'en'),
('class.error.joinFailed', 'پیوستن به کلاس ناموفق بود ({0}).', 'fa'),
('class.error.joinFailed', 'Échec de l''inscription à la classe ({0}).', 'fr'),
('class.error.joinFailed', 'Не удалось присоединиться к занятию ({0}).', 'ru'),
('class.error.onlyCreatorDelete', 'Only the class creator can delete this class.', 'en'),
('class.error.onlyCreatorDelete', 'فقط سازنده کلاس می‌تواند این کلاس را حذف کند.', 'fa'),
('class.error.onlyCreatorDelete', 'Seul le créateur de la classe peut supprimer cette classe.', 'fr'),
('class.error.onlyCreatorDelete', 'Только создатель занятия может удалить это занятие.', 'ru'),
('class.error.classDeleteFailed', 'Failed to delete class ({0}).', 'en'),
('class.error.classDeleteFailed', 'حذف کلاس ناموفق بود ({0}).', 'fa'),
('class.error.classDeleteFailed', 'Échec de la suppression de la classe ({0}).', 'fr'),
('class.error.classDeleteFailed', 'Не удалось удалить занятие ({0}).', 'ru'),
('class.error.classDeleteFailedDetailed', 'Failed to delete class: {0}', 'en'),
('class.error.classDeleteFailedDetailed', 'حذف کلاس ناموفق بود: {0}', 'fa'),
('class.error.classDeleteFailedDetailed', 'Échec de la suppression de la classe : {0}', 'fr'),
('class.error.classDeleteFailedDetailed', 'Не удалось удалить занятие: {0}', 'ru'),
('class.error.notEnrolled', 'You are not enrolled in this class.', 'en'),
('class.error.notEnrolled', 'شما عضو این کلاس نیستید.', 'fa'),
('class.error.notEnrolled', 'Vous n''êtes pas inscrit à cette classe.', 'fr'),
('class.error.notEnrolled', 'Вы не записаны на это занятие.', 'ru'),
('class.error.leaveFailed', 'Failed to leave class ({0}).', 'en'),
('class.error.leaveFailed', 'خروج از کلاس ناموفق بود ({0}).', 'fa'),
('class.error.leaveFailed', 'Échec de la sortie de la classe ({0}).', 'fr'),
('class.error.leaveFailed', 'Не удалось покинуть занятие ({0}).', 'ru'),
('class.error.leaveFailedDetailed', 'Failed to leave class: {0}', 'en'),
('class.error.leaveFailedDetailed', 'خروج از کلاس ناموفق بود: {0}', 'fa'),
('class.error.leaveFailedDetailed', 'Échec de la sortie de la classe : {0}', 'fr'),
('class.error.leaveFailedDetailed', 'Не удалось покинуть занятие: {0}', 'ru'),
('class.confirm.delete.title', 'Delete Class', 'en'),
('class.confirm.delete.title', 'حذف کلاس', 'fa'),
('class.confirm.delete.title', 'Supprimer la classe', 'fr'),
('class.confirm.delete.title', 'Удалить занятие', 'ru'),
('class.confirm.delete.header', 'Are you sure?', 'en'),
('class.confirm.delete.header', 'آیا مطمئن هستید؟', 'fa'),
('class.confirm.delete.header', 'Êtes-vous sûr ?', 'fr'),
('class.confirm.delete.header', 'Вы уверены?', 'ru'),
('class.confirm.delete.content', 'This action will permanently delete this class and all materials.', 'en'),
('class.confirm.delete.content', 'این عملیات کلاس و همه محتواها را برای همیشه حذف می‌کند.', 'fa'),
('class.confirm.delete.content', 'Cette action supprimera définitivement cette classe et tous les supports.', 'fr'),
('class.confirm.delete.content', 'Это действие навсегда удалит занятие и все материалы.', 'ru'),
('class.confirm.leave.title', 'Leave Class', 'en'),
('class.confirm.leave.title', 'خروج از کلاس', 'fa'),
('class.confirm.leave.title', 'Quitter la classe', 'fr'),
('class.confirm.leave.title', 'Покинуть занятие', 'ru'),
('class.confirm.leave.header', 'Leave this class?', 'en'),
('class.confirm.leave.header', 'از این کلاس خارج می‌شوید؟', 'fa'),
('class.confirm.leave.header', 'Quitter cette classe ?', 'fr'),
('class.confirm.leave.header', 'Покинуть это занятие?', 'ru'),
('class.confirm.leave.content', 'You will lose access to class materials until you join again.', 'en'),
('class.confirm.leave.content', 'تا زمانی که دوباره عضو نشوید، به محتوای کلاس دسترسی نخواهید داشت.', 'fa'),
('class.confirm.leave.content', 'Vous perdrez l''accès aux contenus jusqu''à une nouvelle inscription.', 'fr'),
('class.confirm.leave.content', 'Вы потеряете доступ к материалам, пока снова не присоединитесь.', 'ru'),

-- Reviews
('review.title', 'Write a Review', 'en'),
('review.title', 'ارسال بررسی', 'fa'),
('review.title', 'Écrire un avis', 'fr'),
('review.title', 'Оставить отзыв', 'ru'),
('review.file', 'File:', 'en'),
('review.file', 'فایل:', 'fa'),
('review.file', 'Fichier:', 'fr'),
('review.file', 'Файл:', 'ru'),
('review.rating', 'Rating (1 – 5)', 'en'),
('review.rating', 'امتیاز (۱ تا ۵)', 'fa'),
('review.rating', 'Note (1 – 5)', 'fr'),
('review.rating', 'Оценка (1 – 5)', 'ru'),
('review.comment', 'Comment', 'en'),
('review.comment', 'نظر', 'fa'),
('review.comment', 'Commentaire', 'fr'),
('review.comment', 'Комментарий', 'ru'),
('review.comment.prompt', 'Share your feedback about this material…', 'en'),
('review.comment.prompt', 'نظر خود را درباره این محتوا به اشتراک بگذارید…', 'fa'),
('review.comment.prompt', 'Partagez vos commentaires sur ce matériel…', 'fr'),
('review.comment.prompt', 'Поделитесь своим отзывом об этом материале…', 'ru'),
('review.cancel', 'Cancel', 'en'),
('review.cancel', 'لغو', 'fa'),
('review.cancel', 'Annuler', 'fr'),
('review.cancel', 'Отмена', 'ru'),
('review.submit', 'Submit Review', 'en'),
('review.submit', 'ارسال بررسی', 'fa'),
('review.submit', 'Envoyer l''avis', 'fr'),
('review.submit', 'Отправить отзыв', 'ru'),

-- View Reviews
('viewreviews.title', '  Material Reviews', 'en'),
('viewreviews.title', '  بررسی‌های محتوا', 'fa'),
('viewreviews.title', '  Avis sur le matériel', 'fr'),
('viewreviews.title', '  Отзывы о материале', 'ru'),
('viewreviews.file', 'File:', 'en'),
('viewreviews.file', 'فایل:', 'fa'),
('viewreviews.file', 'Fichier:', 'fr'),
('viewreviews.file', 'Файл:', 'ru'),
('viewreviews.close', 'Close', 'en'),
('viewreviews.close', 'بستن', 'fa'),
('viewreviews.close', 'Fermer', 'fr'),
('viewreviews.close', 'Закрыть', 'ru'),
('viewreviews.loading', 'Loading reviews...', 'en'),
('viewreviews.loading', 'بارگذاری بررسی‌ها...', 'fa'),
('viewreviews.loading', 'Chargement des avis...', 'fr'),
('viewreviews.loading', 'Загрузка отзывов...', 'ru')
ON DUPLICATE KEY UPDATE value = VALUES(value);
