sonar.projectKey=OTP1_G9
sonar.projectName=OTP1_G9
sonar.projectVersion=1.0
sonar.sources=src/main/java
sonar.java.binaries=target/classes
sonar.tests=src/test/java
sonar.host.url=http://localhost:9000
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.coverage.exclusions=src/test/**,src/main/java/com/example/app/**